name: fetch

on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2   
        
      - name: Fetch latest articles
        run: Rscript scrape-news.R
        env:
          NEWSAPIKEY: ${{ secrets.NEWSAPIKEY }}
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        
        